### ISSUE TITLE
Create a new Train Script for multi class mobilenet ssd v2 classification !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/gesture-based-rock-paper-scissor#1]
The current train script doesn't work probably, because it was created for binary classification. Please add new train script. P.S. I know the dataset is horrific, working on that right now.

**Comment by gargmanvi** [comment]
Please assign this to me!

**Comment by Nikzy7** [comment]
@gargmanvi done !

**Comment by Nikzy7** [comment]
Thanks !!!!
